### ISSUE TITLE
Add logo to all slides of one presentation

### ISSUE THREAD

**Issue by solrayc** [dzello/reveal-hugo#19] opened 2019-02-12 13:52 UTC
What is the best Hugo friendly way to add a logo image to all of the slides at the same time for just one presentation? Then add a different logo for another presentation?

I use reveal-hugo with an existing Hugo site via theme inheritance functionality. 

I found some suggestions specific to Reveal.js, like [adding ](https://github.com/hakimel/reveal.js/pull/750#issuecomment-35999292)<img ... > to the page body, or [changing CSS](https://github.com/hakimel/reveal.js/issues/1122#issuecomment-335138868), but I couldn't get it to work in Hugo.

It's probably complicated, but I'd like to request a feature of adding logo functionality with front matter, like this:

```
+++
title = "My presentation"
outputs = ["Reveal"]
[reveal_hugo]
theme = "white"
logo = "/image.png"
+++
```

Thanks for reveal-hugo theme.

**Comment by dzello** [comment] 2019-02-12 15:28
Thanks for asking the question and glad you're getting use from the project :)

I went ahead and created an [example presentation(https://reveal-hugo.dzello.com/logo-example/#/) that shows how to accomplish adding a logo.

Reveal.js doesn't have specific logo support afaik but that example will show you how to do it.

To change the logo for different presentations, you can just set different values in the front matter.

Want to give it a try and let me know if it works for you?

**Comment by solrayc** [comment] 2019-02-13 02:46
Hi @dzello , 

I followed your instructions and had some success.

Logo did work with css and img tag added to head.html partial. 
It also works when added to end.html partial. 
But it did not work when added to body.html partial.

When using head.html and end.html partials, the logo would display properly on each slide in presentation, except for pre-printed pdf render. 
With code in head.html logo is formatted correctly, but its only visible on first page.
With code in end.html logo loses its css formatting and is displayed in full size at the center of the first page.

Your example presentation is super cool. It's the best presented github issue response I've ever gotten, by far. Thanks!

**Comment by dzello** [comment] 2019-02-14 11:39
Glad the presentation was helpful!

Can you share the CSS you were using to position the image? If it went away after the first slide, it might be because it wasn't using absolute or fixed position. Unfortunately right now there is no way around that, as it would involve generating logo markup within each slide.

**Comment by solrayc** [comment] 2019-02-17 12:49
This is whats in my `layouts/partials/{section}/reveal-hugo/head.html`

```
<style>
    #logo {
      position: absolute;
      top: 10px;
      right: 10px;
      height: 50px;
    }
  </style>
  <img id="logo" src="{{ .Param "logo.src" }}" alt="{{ .Param "logo.alt" }}">
```

It works just fine this way, thanks so much @dzello .

Just want to report that I couldn't get it to work when I put the same code in body.html (like you did in your demo) instead of head.html.

I tired fixed position, tried renaming img id from "logo" to something custom to prevent potential conflict with theme css, all without luck. The logo would not appear at all.

It works fine with head.html though, and I'm pretty happy with that :)

**Comment by dzello** [comment] 2019-02-18 11:57
Thanks for the extra info, I'll see if I am able to reproduce. Glad it's working :)

**Comment by dzello** [comment] 2019-02-23 10:26
I tried and wasn't able to reproduce, I get the same result for both `body.html` and `head.html`. I'll close this one out for now but if at any point you want to point me to a repo where this is happening I'll happily take a look. Cheers!

**Closed by dzello** 2019-02-23 10:26 UTC
