### ISSUE TITLE
Please add examples of how to set text foreground and background colors...

### ISSUE THREAD

**Issue by dankegel** [dzello/reveal-hugo#6] opened 2018-08-12 05:41 UTC
I know, it shouldn't need an example, but for some reason it's not working here.

**Comment by dzello** [comment] 2018-08-13 17:16
Thanks for opening the issue. Reveal.js doesn't have a great way to change colors other than creating a new theme and pointing to it (which isn't hard but does take a little time). The alternative is adding CSS to the page that overrides the styles from a Reveal.js theme.

For simple cases that'd be my recommendation, and based on that I've added a new feature to reveal-hugo that makes it easier to get custom CSS on the page on a global or per-presentation basis. Have a look at [slides 15-17](https://reveal-hugo.dzello.com/#/15) where layout extension is documented. Essentially, you can create a partial with HTML that will be injected into the page of your presentation. In there you can put a style tag with your CSS customizations.

As far as what CSS to put, I had a very quick look at where color is specified in a Reveal.js CSS theme file. These are the majority of the selectors, set to some colors I made up:

```css
.reveal {
  color: #FFDC00;
}

::selection {
  color: #FFDC00;
  background: #7FDBFF;
}

::-moz-selection {
  color: #FFDC00;
  background: #7FDBFF;
}

section.has-dark-background, section.has-dark-background h1, section.has-dark-background h2, section.has-dark-background h3, section.has-dark-background h4, section.has-dark-background h5, section.has-dark-background h6 {
  color: #FFDC00;
}

section.has-light-background, section.has-light-background h1, section.has-light-background h2, section.has-light-background h3, section.has-light-background h4, section.has-light-background h5, section.has-light-background h6 {
  color: #85144b;
}

.reveal a {
  color: #7FDBFF;
}

.reveal a:hover {
  color: #7FDBFF;
}

.reveal blockquote {
  background: rgba(255, 255, 255, 0.05);
}

.reveal section img {
  background: rgba(255, 255, 255, 0.12);
  border: 4px solid #FFDC00;
}

.reveal a:hover img {
  background: rgba(255, 255, 255, 0.2);
  border-color: #7FDBFF;
}

.reveal .roll span:after {
  color: #FFDC00;
  background: #7FDBFF;
}

.reveal .controls {
  color: #7FDBFF;
}

.reveal .progress {
  background: rgba(0, 0, 0, 0.2);
  color: #7FDBFF;
}

@media print {
  .backgrounds {
    background-color: #85144b;
  }
}
```

If you add those styles to a `reveal-hugo/head.html` partial (or presentation-specific one) and change the colors to the ones that you want, you should have it looking about right.

**Closed** 2018-09-12 22:40 UTC

**Comment by DanielJonesEB** [comment] 2019-03-05 18:15
Hi,

I seem to be getting a very similar error message when trying to use a slide template on Hugo 0.54.0. Using the latest commit on `master` of this repo.

`config.toml` has this:

```
[params.reveal_hugo.templates.title]
class = "title"
background = "#1D74BC"
```

Markdown file is thus:

```
+++
title = "Overview"
outputs = ["Reveal"]
weight = "10"
+++

{{< slide id="overview" template="title" >}}

```

Error is:

```
ERROR 2019/03/05 18:12:58 "/Users/deejay/workspace/k8s-course/slides/content/home/state.md:7:1": failed to render shortcode "slide": failed to process shortcode: "/Users/deejay/workspace/k8s-course/slides/themes/reveal-hugo/layouts/shortcodes/slide.html:1:1": execute of template failed: panic in Execute: reflect: call of reflect.Value.Type on zero Value. See "https://github.com/gohugoio/hugo/issues/5327" for the reason why we cannot provide a better error message for this.
Total in 29 ms
Error: Error building site: "/Users/deejay/workspace/k8s-course/slides/content/home/overview.md:7:1": failed to render shortcode "slide": failed to process shortcode: "/Users/deejay/workspace/k8s-course/slides/themes/reveal-hugo/layouts/shortcodes/slide.html:1:1": execute of template failed: panic in Execute: reflect: call of reflect.Value.Type on zero Value. See "https://github.com/gohugoio/hugo/issues/5327" for the reason why we cannot provide a better error message for this.
```

**Comment by DanielJonesEB** [comment] 2019-03-06 09:38
The issue is here: https://github.com/dzello/reveal-hugo/blob/master/layouts/shortcodes/slide.html#L24

`($.Site.GetPage $.Page.Section).Params.reveal_hugo.templates` is nil if one has put the template definition in `config.toml`, which is a supported use case according to https://reveal-hugo.dzello.com/#/36/1

I've worked around this by changing the shortcode, so there's no rush for a fix in my case, but maybe other users will encounter this.

Thanks for all the hard work, I've generally had a good experience with the theme and we use it for creating presentations as part of training courses.

**Comment by dankegel** [comment] 2019-03-06 16:28
Have you filed a new issue for this yet?

**Comment by DanielJonesEB** [comment] 2019-03-06 16:36
@dankegel No. I can do if that is desired though.

**Comment by dzello** [comment] 2019-03-10 22:46
@DanielJonesEB Yes, if you wouldn't mind opening a new issue I'll get that fixed up.

**Comment by DanielJonesEB** [comment] 2019-03-11 07:44
Done: https://github.com/dzello/reveal-hugo/issues/26
